name = "MCPRepl"
uuid = "b62cb57a-788d-40b5-9d64-84a1dfc37ce3"
authors = ["Hans WÃ¼rfel <git@wuerfel.io>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
Dates = "1.10"
HTTP = "1.10"
JSON = "1.3.0"
REPL = "1.10"
Test = "1.10"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Dates"]
